.func pow 2 4
    push as i32 1
    pop word 2
    push as i32 0
    pop word 3
    jump for_check
label start_for
    push local word 2
    push local word 0
    mul i32
    pop word 2
    inc i32 3
label for_check
    push local word 3
    push local word 1
    jump le i32 start_for
    push local word 2
return word

.func main 0 1
push as i32 2
push as i32 6
call pow
cast i32 i64
syscall PrintI64
return