.str S0 "Time elapsed ¹: "
.str S1 "us\n"

.i64 D0 1000
.i32 W0 1000

.fn main 0 3 4
    # i32 t0 = (i32)(NanoTime() / 1000)
    syscall NanoTime
    push const dword D0
    div i64
    cast i64 i32
    pop word 0

    push as i32 0
    pop word 2
    jump FOR_CHECK

label START_FOR
    inc i32 2
label FOR_CHECK
    push local word 2
    push const word W0
    cmp lt i32
    jump if START_FOR

    # i32 t1 = (i32)(NanoTime() / 1000)
    syscall NanoTime
    push const dword D0
    div i64
    cast i64 i32
    pop word 1

    # Print("Time elapsed : ")
    push const string S0
    syscall Print

    # PrintI64(t1 - t0)
    push local word 1
    push local word 0
    sub i32
    cast i32 i64
    syscall PrintI64

    # Print(" ms\n")
    push const string S1
    syscall Print

    return