

.str S1 "Bot : Tell me something\n"
.str S2 "Me : "
.str S3 "Bot : You really told me \""
.str S4 "\"\n"

.fn main 0 4 
    # Print("Bot : Tell me something\n")
    push const string S1
    syscall Print

    # Print("Me : ")
    push const string S2
    syscall Print

    # char buffer[16]
    # Scan(buffer, 16)
    push ref 0    
    push as i32 16
    syscall Scan
    
    # Print("Bot : You really told me ")
    push const string S3
    syscall Print

    # Print(buffer)
    push ref 0
    syscall Print

    # Print("\"\n")
    push const string S4
    syscall Print

    return