.i32 N 1000

.str value_is "Value is : "
.str nl "\n"

.fn main 0 2
    push const word N
    call recSuma
    push const string value_is
    syscall Print
    cast i32 i64
    syscall PrintI64
    push const string nl
    syscall Print
    return

.fn recSum 1 1
    push local word 0
    push as i32 0
    cmp gt i32
    jump if RET
    push local word 0
    return word
label RET
    push local word 0
    push as i32 1
    sub i32
    call recSum
    push local word 0
    add i32
    return word

